name: Deploy to Server

on:
  push:
    branches:
      - main # Déclencher l'action sur les push vers la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Vérifier le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurer SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 207.154.255.72 >> ~/.ssh/known_hosts

      # 3. Déployer sur le serveur
      - name: Deploy application
        run: |
          ssh -o StrictHostKeyChecking=no root@207.154.255.72 << 'EOF'
            cd /var/www/laravel || git clone git@github.com:<utilisateur>/<repo>.git /var/www/laravel
            cd /var/www/laravel
            git pull origin main
            # Ajouter des commandes spécifiques pour votre application
            npm install
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            chown -R www-data:www-data storage bootstrap/cache
            chmod -R 775 storage bootstrap/cache
            php artisan queue:restart
            php artisan cache:clear
          EOF

      - name: Notify Deployment Success
        run: echo "Deployment completed successfully!"
