name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PUSH_TOKEN }}
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
#      - run: npm run build
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          username: root
          host: 207.154.255.72
          script: 'cd /var/www/laravel && ./scripts/server_deploy.sh'
